server:
  servlet:
    context-path: /mine
  port: 8083



#自定义数据源
spring:
  jdbc:
    datasource:
      mine:
        url: jdbc:mysql://localhost:3306/mine?useSSL=false&serverTimezone=UTC
        username: root
        password: root
        driverClassName: com.mysql.cj.jdbc.Driver
        initialSize: 2
        minIdle: 2
        maxActive: 10
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
      mine1:
        url: jdbc:mysql://localhost:3306/mine1?useSSL=false&serverTimezone=UTC
        username: root
        password: root
        driverClassName: com.mysql.cj.jdbc.Driver
        initialSize: 2
        minIdle: 2
        maxActive: 10
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
mybatis:
  mapper-locations: classpath:mapper/*.xml